name: Build flatpak manually
on:
  workflow_dispatch:

jobs:
  flatpak:
    name: "Build flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        if: ${{ matrix.arch != 'x86_64' }}
        run: |
          # Use the static binaries because it's unable to use a package manager 
          curl https://download.docker.com/linux/static/stable/x86_64/docker-26.0.0.tgz --output ./docker.tgz
          tar xzvf docker.tgz
          mv docker/* /usr/bin
      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build App (Native x86_64)
        if: matrix.arch == 'x86_64'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - if: matrix.arch == 'x86_64'
        run: ./gradlew packageAppImage

      - name: Build App (Emulated aarch64)
        if: matrix.arch == 'aarch64'
        run: |
          # We run the build inside an ARM64 container via QEMU
          docker run --rm --platform linux/arm64 \
            -v ${{ github.workspace }}:/home/gradle/project \
            -w /home/gradle/project \
            gradle:8-jdk17 \
            ./gradlew packageAppImage

      - name: Copy appImage
        run: cp -r composeApp/build/compose/binaries/main/app/kitshn flatpak/source

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: app.kitshn.kitshn.flatpak
          manifest-path: flatpak/app.kitshn.kitshn.yml
          cache-key: flatpak-builder-${{ matrix.arch }}-${{ github.sha }}
          arch: ${{ matrix.arch }}
